--data_wide_cb_budgetuse
--data_wide_cb_budgetuse
SELECT  a.BudgetUseContractGUID AS BudgetUseGUID ,
        1 AS BillTypeEnum ,
        '合同' AS BillType ,
        a.ContractGUID AS BillGUID ,
        b.SignDate AS BillDate ,
        b.ContractCode AS BillCode ,
        b.ContractName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum ,
        b.ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseContract a
        LEFT JOIN dbo.cb_Contract b ON a.ContractGUID = b.ContractGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseBcContractGUID AS BudgetUseGUID ,
        2 AS BillTypeEnum ,
        '补充合同' AS BillType ,
        a.BcContractGUID AS BillGUID ,
        b.JbDate AS BillDate ,
        b.ContractCode AS BillCode ,
        b.ContractName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        a.IsMasterContract AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum ,
        b.ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		CASE WHEN b.SupTypeEnum = 1 THEN a.CfAmount ELSE 0 END AS ActualCost,
		CASE WHEN b.SupTypeEnum = 1 THEN a.CfAmountNonTax ELSE 0 END  AS ActualCostNonTax
FROM    dbo.cb_BudgetUseBcContract a
        LEFT JOIN dbo.cb_BcContract b ON a.BcContractGUID = b.BcContractGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseSubContractGUID AS BudgetUseGUID ,
        3 AS BillTypeEnum ,
        '分包合同' AS BillType ,
        a.SubContractGUID AS BillGUID ,
        b.JbDate AS BillDate ,
        b.ContractCode AS BillCode ,
        b.ContractName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum ,
        b.ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseSubContract a
        LEFT JOIN dbo.cb_SubContract b ON a.SubContractGUID = b.SubContractGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseHTFKApplyForDirectGUID AS BudgetUseGUID ,
        4 AS BillTypeEnum ,
        '无合同付款申请' AS BillType ,
        a.HTFKApplyGUID AS BillGUID ,
        b.ApplyDate AS BillDate ,
        b.ApplyCode AS BillCode ,
        b.[Subject] AS BillName ,
        NULL AS ContractGUID ,
        NULL AS IsMasterContract ,
        a.HTFKApplyGUID AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApplyStateEnum AS ApproveStateEnum ,
        b.ApplyState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.YfAmount AS CfAmount ,
        a.YfAmountNonTax AS CfAmountNonTax ,
        a.YfAmount AS YfAmount ,
        a.YfAmountNonTax AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		a.ActualCost,
		a.ActualCostNonTax
FROM    dbo.cb_BudgetUseHTFKApplyForDirect a
        LEFT JOIN dbo.cb_HTFKApplyForDirect b ON a.HTFKApplyGUID = b.HTFKApplyGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseOfHtFKApplyGUID AS BudgetUseGUID ,
        5 AS BillTypeEnum ,
        '合同付款申请' AS BillType ,
        a.HTFKApplyGUID AS BillGUID ,
        b.ApplyDate AS BillDate ,
        b.ApplyCode AS BillCode ,
        b.[Subject] AS BillName ,
        b.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApplyStateEnum AS ApproveStateEnum ,
        b.ApplyState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        0 AS CfAmount ,
        0 AS CfAmountNonTax ,
        a.YfAmount AS YfAmount ,
        a.YfAmountNonTax AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		a.ActualCost,
		a.ActualCostNonTax
FROM    dbo.cb_BudgetUseOfHtFKApply a
        LEFT JOIN dbo.cb_HTFKApply b ON a.HTFKApplyGUID = b.HTFKApplyGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.AlterBudgetUseGUID AS BudgetUseGUID ,
        6 AS BillTypeEnum ,
        '设计变更' AS BillType ,
        a.AlterGUID AS BillGUID ,
        b.ReportDate AS BillDate ,
        b.AlterCode AS BillCode ,
        b.AlterName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        e.AlterToContractGUID AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount AS CfAmount ,
        a.CfAmountNonTax AS CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_DesignAlterApplyBudgetUse a
        LEFT JOIN dbo.cb_DesignAlterApply b ON a.AlterGUID = b.AlterGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
        LEFT JOIN dbo.cb_DesignAlterApplyToContract e ON a.AlterGUID = e.AlterGuid
                                                    AND a.ContractGUID = e.ContractGUID
UNION ALL
SELECT  a.AlterBudgetUseGUID AS BudgetUseGUID ,
        7 AS BillTypeEnum ,
        '设计变更完工确认' AS BillType ,
        a.AlterGUID AS BillGUID ,
        b.SignDate AS BillDate ,
        b.BudgetNumber AS BillCode ,
        b.AlterZjspName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        b.AlterGUID AS AlterGUID ,
        e.AlterToContractGUID AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        --a.CfAmount - a.AlterCfAmount AS CfAmount ,
        --a.CfAmountNonTax - a.AlterCfAmountNonTax AS CfAmountNonTax ,
        a.CfAmount AS CfAmount ,
        a.CfAmountNonTax AS CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        a.AlterCfAmount AS AlterCfAmount ,
        a.AlterCfAmountNonTax AS AlterCfAmountNonTax ,
        (a.AlterCfAmount - a.AlterCfAmountNonTax) AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_DesignAlterCostConfirmBudgetUse a
        LEFT JOIN dbo.cb_DesignAlterCostConfirm b ON a.AlterGUID = b.AlterZJSPGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
        LEFT JOIN dbo.cb_DesignAlterApplyToContract e ON b.AlterGUID = e.AlterGuid
                                                    AND b.ContractGUID = e.ContractGUID
UNION ALL
SELECT  a.AlterBudgetUseGUID AS BudgetUseGUID ,
        8 AS BillTypeEnum ,
        '现场签证' AS BillType ,
        a.AlterGUID AS BillGUID ,
        b.ReportDate AS BillDate ,
        b.AlterCode AS BillCode ,
        b.AlterName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        b.AlterGUID AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_LocaleAlterApplyBudgetUse a
        LEFT JOIN dbo.cb_LocaleAlterApply b ON a.AlterGUID = b.AlterGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.AlterBudgetUseGUID AS BudgetUseGUID ,
        20 AS BillTypeEnum ,
        '材料调差' AS BillType ,
        a.AlterGUID AS BillGUID ,
        b.ReportDate AS BillDate ,
        b.AlterCode AS BillCode ,
        b.AlterName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        b.AlterGUID AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_MaterialDiffApplyBudgetUse a
        LEFT JOIN dbo.cb_MaterialDiffApply b ON a.AlterGUID = b.AlterGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.AlterBudgetUseGUID AS BudgetUseGUID ,
        9 AS BillTypeEnum ,
        '现场签证完工确认' AS BillType ,
        a.AlterGUID AS BillGUID ,
        b.SignDate AS BillDate ,
        b.BudgetNumber AS BillCode ,
        b.AlterZjspName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        b.AlterGUID AS AlterGUID ,
        b.AlterGUID AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        --a.CfAmount - a.AlterCfAmount AS CfAmount ,
        --a.CfAmountNonTax - a.AlterCfAmountNonTax AS CfAmountNonTax ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        a.AlterCfAmount AS AlterCfAmount ,
        a.AlterCfAmountNonTax AS AlterCfAmountNonTax ,
        (a.AlterCfAmount - a.AlterCfAmountNonTax) AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_LocaleAlterCostConfirmBudgetUse a
        LEFT JOIN dbo.cb_LocaleAlterCostConfirm b ON a.AlterGUID = b.AlterZjspGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseHTBalanceGUID AS BudgetUseGUID ,
        12 AS BillTypeEnum ,
        '合同结算' AS BillType ,
        a.HTBalanceGUID AS BillGUID ,
        b.JsDate AS BillDate ,
        b.BalanceDocNo AS BillCode ,
        b.BalanceName AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmountMargin AS CfAmount ,
        a.CfAmountMarginNonTax AS CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        a.CfAmount AS SfAmount ,
        a.CfAmountNonTax AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		BxAmount AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseHTBalance a
        LEFT JOIN dbo.cb_HTBalance b ON a.HTBalanceGUID = b.HTBalanceGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseOfReceiptPayGUID AS BudgetUseGUID ,
        13 AS BillTypeEnum ,
        '付款登记' AS BillType ,
        a.VoucherGUID AS BillGUID ,
        b.KpDate AS BillDate ,
        b.VoucherCode AS BillCode ,
        b.[Subject] AS BillName ,
        CASE WHEN b.RefTypeEnum = 1 THEN b.ContractGUID
             ELSE NULL
        END AS ContractGUID ,
        NULL AS IsMasterContract ,
        CASE WHEN b.RefTypeEnum = 2 THEN b.RefGUID
             ELSE NULL
        END AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        3 AS ApproveStateEnum ,
        '已审核' AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.ProfitOrLossAmount AS CfAmount ,
        a.ProfitOrLossAmountNonTax AS CfAmountNonTax ,
        a.ProfitOrLossAmount AS YfAmount ,
        a.ProfitOrLossAmountNonTax AS YfAmountNonTax ,
        a.CfAmount AS SfAmount ,
        a.CfAmountNonTax AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseOfReceiptPay a
        LEFT JOIN dbo.cb_Voucher b ON a.VoucherGUID = b.VoucherGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseDeductGUID AS BudgetUseGUID ,
        14 AS BillTypeEnum ,
        '扣款' AS BillType ,
        a.DeductGUID AS BillGUID ,
        b.JbDate AS BillDate ,
        b.DeductCode AS BillCode ,
        b.[Subject] AS BillName ,
        a.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        c.AccountCode AS CostCode ,
        c.AccountShortName AS CostName ,
        a.CfAmount AS CfAmount ,
        a.CfAmountNonTax AS CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseDeduct a
        LEFT JOIN dbo.cb_Deduct b ON a.DeductGUID = b.DeductGUID
        LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL
SELECT  a.BudgetUseRefundBillGUID AS BudgetUseGUID ,
        15 AS BillTypeEnum ,
        '退款' AS BillType ,
        a.RefundBillGUID AS BillGUID ,
        b.JbDate AS BillDate ,
        c.VoucherCode AS BillCode ,
        c.[Subject] AS BillName ,
        NULL AS ContractGUID ,
        NULL AS IsMasterContract ,
        c.RefGUID AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        3 AS ApproveStateEnum ,
        '已审核' AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        d.AccountCode AS CostCode ,
        d.AccountShortName AS CostName ,
        a.CfAmount ,
        a.CfAmountNonTax ,
        a.CfAmount AS YfAmount ,
        a.CfAmountNonTax AS YfAmountNonTax ,
        a.CfAmount AS SfAmount ,
        a.CfAmountNonTax AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_BudgetUseRefundBill a
        LEFT JOIN dbo.cb_FefundBill b ON a.RefundBillGUID = b.FefundBillGUID
        LEFT JOIN dbo.cb_Voucher c ON b.RefGUID = c.VoucherGUID
        LEFT JOIN dbo.cb_StageAccount d ON a.CostGUID = d.StageAccountGUID
UNION ALL
SELECT  a.YgAlterAdjustDtlGUID AS BudgetUseGUID ,
        16 AS BillTypeEnum ,
        '预留金调整单' AS BillType ,
        a.YgAlterAdjustGUID AS BillGUID ,
        b.AdjustDate AS BillDate ,
        NULL AS BillCode ,
        b.[Subject] AS BillName ,
        b.ContractGUID AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        b.ApproveStateEnum AS ApproveStateEnum ,
        b.ApproveState AS ApproveState ,
        a.ProjectGUID ,
        a.BudgetGUID ,
        a.CostGUID ,
        d.AccountCode AS CostCode ,
        d.AccountShortName AS CostName ,
        a.CurAdjustAmount AS CfAmount ,
        a.CurAdjustAmountNonTax AS CfAmountNonTax ,
        0 AS YfAmount ,
        0 AS YfAmountNonTax ,
        0 AS SfAmount ,
        0 AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_YgAlterAdjustDtl a
        LEFT JOIN dbo.cb_YgAlterAdjust b ON a.YgAlterAdjustGUID = b.YgAlterAdjustGUID
        LEFT JOIN dbo.cb_StageAccount d ON a.CostGUID = d.StageAccountGUID
UNION ALL
SELECT  a.ImportFeeFileFtDetailGUID AS BudgetUseGUID ,
        17 AS BillTypeEnum ,
        '三费导入' AS BillType ,
        a.ImportFeeFileGUID AS BillGUID ,
        c.BusinessDate AS BillDate ,
        NULL AS BillCode ,
        b.[FileName] AS BillName ,
        NULL AS ContractGUID ,
        NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
        3 AS ApproveStateEnum ,
        '已审核' AS ApproveState ,
        a.ProjectGuid ,
        a.BudgetGUID ,
        a.CostGuid ,
        d.AccountCode AS CostCode ,
        d.AccountShortName AS CostName ,
        a.FtAmount AS CfAmount ,
        a.FtAmountNonTax AS CfAmountNonTax ,
        a.FtAmount AS YfAmount ,
        a.FtAmountNonTax AS YfAmountNonTax ,
        a.FtAmount AS SfAmount ,
        a.FtAmountNonTax AS SfAmountNonTax ,
        NULL AS AlterCfAmount ,
        NULL AS AlterCfAmountNonTax ,
        NULL AS AlterCfAmountInputTax,
		NULL AS ActualCost,
		NULL AS ActualCostNonTax
FROM    dbo.cb_ImportFeeFileFtDetail a
		LEFT JOIN dbo.cb_ImportFeeFileDetail c ON a.ImportFeeFileDetailGUID = c.ImportFeeFileDetailGUID 
		LEFT JOIN dbo.cb_ImportFeeFile b ON a.ImportFeeFileGUID = b.ImportFeeFileGUID
        LEFT JOIN dbo.cb_StageAccount d ON a.CostGuid = d.StageAccountGUID
UNION ALL
SELECT 
a.BudgetUseProgressPaymentGUID AS BudgetUseGUID,
18 AS BillTypeEnum,
'应付进度款' AS BillType,
a.ProgressPaymentGUID AS BillGUID,
b.ApplyDate AS BillDate,
b.ReportCode AS BillCode,
b.Subject AS BillName,
a.ContractGUID AS ContractGUID,
 NULL AS IsMasterContract ,
        NULL AS HTFKApplyGUID ,
        NULL AS AlterGUID ,
        NULL AS FactTableAlterGUID ,
		b.ApproveStateEnum,
		b.ApproveState,
		a.ProjectGUID,
		a.BudgetGUID,
		a.CostGUID,
		c.AccountCode AS CostCode,
		c.AccountShortName AS CostName,
		a.CfAmount AS CfAmount,
		a.CfAmountNonTax AS CfAmountNonTax,
		0 AS YfAmount,
		0 AS YfAmountNonTax,
		0 AS SfAmount,
		0 AS SfAmountNonTax,
		NULL AS AlterCfAmount,
		NULL AS AlterCfAmountNonTax,
		NULL AS AlterCfAmountInputTax,
		a.CfAmount AS ActualCost,
		a.CfAmountNonTax AS  ActualCostNonTax
FROM dbo.cb_BudgetUseProgressPayment a
LEFT JOIN dbo.cb_ProgressPayment b ON b.ProgressPaymentGUID = a.ProgressPaymentGUID
LEFT JOIN dbo.cb_StageAccount c ON a.CostGUID = c.StageAccountGUID
UNION ALL

SELECT 
cbuoi.BudgetUseOfInvoiceGUID AS BudgetUseGUID,
19 AS BillTypeEnum,
'发票管理' AS BillType,
a.InvoiceGUID AS BillGUID,
a.KpDate AS BillDate,
a.InvoiceNO AS BillCode,
a.InvoiceCategory + '_' + a.InvoiceNO AS BillName,
CASE a.InvoiceRefTypeEnum
       WHEN 1 THEN a.RefGUID ELSE NULL END AS ContractGUID,
NULL AS IsMasterContract ,
CASE a.InvoiceRefTypeEnum 
       WHEN 1 THEN NULL ELSE a.RefGUID END AS HTFKApplyGUID,
NULL AS AlterGUID ,
NULL AS FactTableAlterGUID ,
a.ApproveStateEnum,
a.ApproveState,
cbuoi.ProjectGUID AS ProjectGUID,
cbuoi.BudgetGUID,
cbuoi.CostGUID,
c.AccountCode AS CostCode,
c.AccountShortName AS CostName,
cbuoi.CfAmount AS CfAmount,
cbuoi.CfAmountNonTax AS CfAmountNonTax,
0 AS YfAmount,
0 AS YfAmountNonTax,
0 AS SfAmount,
0 AS SfAmountNonTax,
NULL AS AlterCfAmount,
NULL AS AlterCfAmountNonTax,
NULL AS AlterCfAmountInputTax,
0 AS ActualCost,  -- 实际金额
0 AS  ActualCostNonTax  --实际成本(不含税)
FROM cb_BudgetUseOfInvoice cbuoi
LEFT JOIN  dbo.cb_Invoice a ON a.InvoiceGUID = cbuoi.InvoiceGUID
LEFT JOIN dbo.cb_StageAccount c ON cbuoi.CostGuid = c.StageAccountGUID
